Saving trials if flag turned on after a trial is finished
levante-framework/core-tasks pull request #62
Opened 2024-04-24 14:47 UTC by asengupta3

2024-04-24 18:00 UTC, Zio-4 requested changes

2024-04-24 18:00 UTC, Zio-4 commented on task-launcher/src/tasks/shared/helpers/initTrialSaving.js
>      config.firekit.finishRun();
The logic here actually doesn't need any change. In afcStimulus.js, in the shared folder, in the on_finish function, we should check if the final data includes the corpus trial type, and if not, add it to the data object. The trial type will come from the current stimulus object. It looks like there is a trialType property being saved but perhaps it is being overwritten by jsPsych after our code.

2024-04-25 20:04 UTC, asengupta3 commented
@Zio-4 I am seeing it now in the DB (please see the screenshot in the description), but not trials have it, I wonder why. The ones that don't have it looks like this:
<img width="1431" alt="Screenshot 2024-04-26 at 1 34 07 AM" src="https://github.com/levante-framework/core-tasks/assets/91208213/f3d3ba28-3a11-46f7-8355-0174adb0e536">

2024-04-26 00:37 UTC, Zio-4 requested changes
Looks good. Could you remove the logs? We don't have any blocks currently so after that you can merge it. Thanks!

2024-04-26 00:38 UTC, Zio-4 commented
Responding to your comment: It seems to be instruction trials don't save the trial type. I tested and noticed this on Math. This is fine. In fact, we don't want to write any instruction trials to the DB so we can add that to the backlog.

2024-04-26 16:21 UTC, merged