Memory game update
levante-framework/core-tasks pull request #63
Opened 2024-04-26 00:29 UTC by Zio-4

- Adding memory game translations, 
- instructions, 
- reverse phase, 
- increasing sequence length
- Adding toast notification for encouragement after 10 seconds of inactivity (not clicking squares)
- Changes for practice trials
- New graphic from Figma designs
- Adding audio cue for display stage and input stage
- Extracting audio setup into a reusable function (afcStimulus, stimulus in Memory Game)
- Other minor changes

2024-04-26 02:04 UTC, asengupta3 commented on task-launcher/src/tasks/memory-game/trials/stimulus.js
> +const numOfblocks = age > 12 ? 9 : 4;
Move this to a constant, since it is being reused?

2024-04-26 02:04 UTC, asengupta3 commented on task-launcher/src/tasks/shared/trials/feedback.js
> +}
NIT: New line and there is one below as well.

2024-04-26 02:05 UTC, asengupta3 commented on task-launcher/src/index.js
> +    console.log({ mediaAssets });
Do we want to log this in the console for the prod app? I removed this in my PR.

2024-04-30 23:29 UTC, Zio-4 commented
@kachergis @asengupta3 @anabonne Could one of you look over this PR when you get a chance? It's pretty big and I probably should have made it into smaller PRs.

2024-05-01 18:36 UTC, kachergis commented on task-launcher/src/index.js
> +    } else {
I'm also not sure this is what was intended (or what the intention was). Also want to point out that we can make the task name `memory-game` if that's helpful?

2024-05-01 18:39 UTC, kachergis commented on task-launcher/src/styles/task.scss
do these changes have any undesirable side effects for other tasks? unclear to me, but I can test if @Zio-4 points out overlap

2024-05-01 18:49 UTC, kachergis commented on task-launcher/src/tasks/shared/helpers/replayAudio.js
> +    const replayBtn = document.getElementById('replay-btn');
good point, @anabonne ! for expediency, @Zio-4  if you don't have time now make a ticket..

2024-05-01 19:00 UTC, Zio-4 commented on task-launcher/src/index.js
> +    } else {
No, it means that any task that is not memory game will hit the first case. Otherwise if it is memory game, we hit the else case.

2024-05-01 19:02 UTC, kachergis requested changes
Good work! Getting very close -- minimally today, please look at the logic issue Adrien raised. There is missing audio prompts and audio feedback (and replay buttons). I think it would also be good to add a text instruction prompt to the beginning of each new sequence during test (or any other indicator that the child should begin responding).

2024-05-01 19:05 UTC, Zio-4 commented on task-launcher/src/tasks/shared/helpers/replayAudio.js
> +    const replayBtn = document.getElementById('replay-btn');
Good point. I should advertise the requirment. We want the id to alwayve be the same since it also has the CSS for the element.

2024-05-01 19:11 UTC, Zio-4 commented on task-launcher/src/tasks/shared/trials/finishExperiment.js
Will make a ticket for the backlog. I just copied that line with the existing code. This is also part of the larger issue that we are using session storage for (almost) everything which can create bugs when playing tasks in succession.

2024-05-01 20:12 UTC, merged

2024-05-01 21:15 UTC, anabonne commented on task-launcher/src/index.js
> +    } else {
Wow sorry I completely misread the first condition.